Update Fastify and all other dependencies
jsumners/fastify-no-icon pull request #2
Opened 2020-08-11 09:31 UTC by gilles-crealp

- Update to Fastify ^3.0.0
- Update tests

2020-08-11 11:30 UTC, jsumners requested changes

2020-08-11 11:30 UTC, jsumners commented on package.json
> +  "version": "4.0.0",
I will handle this. Please revert.

2020-08-11 11:38 UTC, gilles-crealp commented on package.json
> +  "version": "4.0.0",
No problem.

2020-08-11 11:42 UTC, jsumners approved these changes
Thank you. This looks good. I will merge and release when I am able.

2020-08-14 00:52 UTC, merged

2020-08-14 00:55 UTC, jsumners commented
Sorry for the delay. This has been released as v4.0.0.